# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      build_command:
        required: true
        type: string
      artifacts_publish_command:
        required: false
        type: string
      image_name:
        required: false
        type: string
      docker_build_command:
        required: false
        type: string
      service_name:
        required: false
        type: string
      deploy_repo:
        required: false
        type: string
      slack_channel_id:
        required: false
        type: string
    # Map the workflow outputs to job outputs
    outputs:
      image_version:
        description: "Image version"
        value: ${{ jobs.build.outputs.output1 }}
    secrets:
      maven_repo_access_token:
        description: 'Maven repo access token'
        required: false
      maven_user:
        description: 'MAVEN_USER'
        required: true
      maven_password:
        description: 'MAVEN_PASSWORD'
        required: true
      slack_bot_token:
        description: 'SLACK_BOT_TOKEN'
        required: false
      slack_channel_id:
        description: 'SLACK_CHANNEL_ID'
        required: false
      deploy_repo_token:
        description: 'Deploy repo token'
        required: false


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Initialize variables
        id: vars
        run: |
          echo "::set-output name=run_url::https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Building project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ inputs.build_command }} -PmavenUser=${{ secrets.maven_user }} -PmavenPassword=${{ secrets.maven_password }}

      - name: Publish Artifacts
        uses: gradle/gradle-build-action@v2
        if: ${{ success() && inputs.artifacts_publish_command != 0 }}
        with:
          arguments: ${{ inputs.artifacts_publish_command }}

      - name: Post to a Slack channel
        id: slack
        if: ${{ failure() && inputs.slack_channel_id != 0 }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_bot_token }}
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: ${{ inputs.slack_channel_id }}  # Slack channel id or user id to post message. https://api.slack.com/methods/chat.postMessage#channels
          slack-message: Deployment failed ${{ steps.vars.outputs.run_url }}

