# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      build_command:
        required: true
        type: string
      artifacts_publish_command:
        required: false
        type: string
      image_name:
        required: false
        type: string
      docker_build_command:
        required: false
        type: string
      service_name:
        required: false
        type: string
      deploy_repo:
        required: false
        type: string
      slack_channel_id:
        required: false
        type: string
    # Map the workflow outputs to job outputs
    outputs:
      image_version:
        description: "Image version"
        value: ${{ jobs.build.outputs.output1 }}
    secrets:
      maven_repo_access_token:
        description: 'Maven repo access token'
        required: false
      aws_account_id:
        description: 'AWS_ACCOUNT_ID'
        required: true
      aws_access_key_id:
        description: 'AWS_ACCESS_KEY_ID'
        required: true
      aws_secret_access_key_id:
        description: 'AWS_SECRET_ACCESS_KEY'
        required: true
      slack_bot_token:
        description: 'SLACK_BOT_TOKEN'
        required: false
      slack_channel_id:
        description: 'SLACK_CHANNEL_ID'
        required: false
      deploy_repo_token:
        description: 'Deploy repo token'
        required: false
      meawallet_maven_password:
        description: 'Meawallet Maven Password'
        required: false        


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.vars.outputs.image_version }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key_id }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        if: ${{ inputs.docker_build_command != 0 }}
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Initialize variables
        id: vars
        run: |
          codeartifact_token=$(aws codeartifact get-authorization-token --domain meapay-app --domain-owner ${{ secrets.aws_account_id }} --query authorizationToken --output text)
          echo "::add-mask::$codeartifact_token"
          echo "::set-output name=codeartifact_auth_token::$codeartifact_token"
          echo "::set-output name=image_version::$(./gradlew -q printVersion)"
          echo "::set-output name=run_url::https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Preparing build
        # not all repos have local properties file
        if: hashFiles('local.properties-template') != ''
        env:
          MAVEN_REPO_PAT: ${{ secrets.maven_repo_access_token }}
        run: |
          # Configuring credentials for Gradle connection to Azure Artifacts
          sed -i "s/PERSONAL_ACCESS_TOKEN/$MAVEN_REPO_PAT/g" local.properties-template
          mv local.properties-template local.properties

      - name: Building project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ inputs.build_command }} -PmavenUser=aws -PmavenPassword=${{ steps.vars.outputs.codeartifact_auth_token }} -PmeawalletMavenPassword=${{ secrets.meawallet_maven_password }}

      - name: Publish Artifacts
        uses: gradle/gradle-build-action@v2
        if: ${{ success() && inputs.artifacts_publish_command != 0 }}
        with:
          arguments: ${{ inputs.artifacts_publish_command }} -PmavenUser=aws -PmavenPassword=${{ steps.vars.outputs.codeartifact_auth_token }}

      - name: Create Docker Image
        if: ${{ success() && inputs.docker_build_command != 0 }}
        env:
          DOCKER_IMAGE_NAME: ${{ inputs.image_name }}
          IMAGE_VERSION: ${{ steps.vars.outputs.image_version }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ inputs.docker_build_command }} -Dquarkus.container-image.image=${{ inputs.image_name }}:${{ steps.vars.outputs.image_version }}

      - name: Push image to remote registry
        if: ${{ success() && inputs.docker_build_command != 0 }}
        run: |
          docker push ${{ inputs.image_name }}:${{ steps.vars.outputs.image_version }}

      - name: Dispatch deploy-dev event
        if: ${{ success() && inputs.service_name != 0 && inputs.deploy_repo != 0 }}
        run: |
          curl -d "{\"event_type\": \"deploy-dev\", \"client_payload\": { \"service_name\": \"${{ inputs.service_name }}\", \"image_version\": \"${{ steps.vars.outputs.image_version }}\"}}" \
          -H "Content-Type: application/json" -H "Authorization: token ${{ secrets.deploy_repo_token }}" \
          -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${{ inputs.deploy_repo }}/dispatches"

      - name: Post to a Slack channel
        id: slack
        if: ${{ failure() && inputs.slack_channel_id != 0 }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_bot_token }}
        uses: slackapi/slack-github-action@v1.16.0
        with:
          channel-id: ${{ inputs.slack_channel_id }}  # Slack channel id or user id to post message. https://api.slack.com/methods/chat.postMessage#channels
          slack-message: Deployment failed ${{ steps.vars.outputs.run_url }}

